import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/app/_trpc/Provider";
import { Suspense } from "react";
import Navbar from "@/components/layout/navbar";

const inter = Inter({ subsets: ["latin"] });
const baseUrl = process.env.PUBLIC_URL
  ? `https://${process.env.PUBLIC_URL}`
  : "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
        <Navbar />
        <Suspense fallback={<div>...loading</div>}>
          <Provider>{children}</Provider>
        </Suspense>
      </body>
    </html>
  );
}
